### ISSUE TITLE
Remove the link from the logo

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/Casper#7]

**Comment by tagawa** [comment]
Not sure about this. The logo being clickable is kind of expected behaviour (at least in my experience), but as it's the main DDG logo we could link it to duckduckgo.com instead of spreadprivacy.com

**Comment by jagtalon** [comment]
Hey, @tagawa! Totally agree with this, but initially we need to not link it anywhere just like in https://duckduckgo.com/about.

For the next iteration I think we definitely have to make a decision, but it's something that should be consistent everywhere.
